name: Build iOS Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Theos Framework & Dependencies
      run: |
        export THEOS=~/theos
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=~/theos" >> $GITHUB_ENV
        
    - name: Setup iOS SDK
      run: |
        mkdir -p ~/theos/sdks
        curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
        unzip -q master.zip
        mv sdks-master/* ~/theos/sdks/
        rm -rf master.zip sdks-master

    - name: Unzip Project Files
      run: |
        unzip Drawdylib.zip -d ./project_extracted
        if [ -d "./project_extracted/Drawdylib" ]; then
          mv ./project_extracted/Drawdylib/* .
        else
          mv ./project_extracted/* .
        fi

    - name: Compile Tweak Package
      run: |
        export THEOS=~/theos
        make package FINALPACKAGE=1

    - name: Upload Compiled Artifact (.deb / .dylib)
      uses: actions/upload-artifact@v4
      with:
        name: OsirisDrawESP-Build
        path: packages/*.deb
